### ISSUE TITLE
Visual Studio 2022 Support PLEASEEE!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Mike-E-angelo** [tunnelvisionlabs/MouseNavigation#31]
PRETTY PLEASEEEEEEEEEEEEE :) :) :)

**Comment by xnorxnor** [comment]
As a workaround, you can use "X-Mouse Button Control".
Create a profile for devenv.exe, assign "Simulated Keys" to back and forward mouse buttons. Set "{CTRL}-" for mouse button 4 (back) and "{CTRL}{SHIFT}-" for mouse button 4 (forward). 
Works for me.

**Comment by Mike-E-angelo** [comment]
Indeed, works for me as well, @xnorxnor.  At least, for the interim.  Thank you for the workaround. 👍

**Comment by Rubenisme** [comment]
[I created a PR for this](https://github.com/tunnelvisionlabs/MouseNavigation/pull/32), probably needs editing by @sharwell to publish to VS market-place and appveyor error, but you can build it locally (I suggest in release mode) and this builds a builds a VSIX package for you to install it.

**Comment by JanFiedler2503** [comment]
Maybe could be resolved by this Pull Request ? [https://github.com/tunnelvisionlabs/MouseNavigation/pull/32](url)

**Comment by sharwell** [comment]
Visual Studio 2022 has this feature built in, and it's even better than this extension because doesn't suffer from #4. I'm not aware of any reason why I would need to publish an update?

**Comment by sharwell** [comment]
Even the later builds of Visual Studio 2019 have this feature built in (version 16.7 and newer):
https://github.com/dotnet/roslyn/pull/48717

**Comment by Mike-E-angelo** [comment]
Thank you for looking into this @sharwell. I personally can attest that the mouse navigation does not work as expected for me in Visual Studio 2022 unless I have X-Mouse configured as per above.  Unless there is a setting that must be toggled (or I have something very messed up in my settings, which is entirely possible), there still seems to be a disconnect with Visual Studio mouse navigation.

**Comment by sharwell** [comment]
@Mike-E-angelo it looks like this feature is included in all configurations, and it's not trivial to disable it or bypass it with an extension. It seems likely that an operating system level application is intercepting or altering the commands from the mouse in a way that prevents the Back and Forward buttons from translating to Back and Forward commands within the application.

**Comment by Mike-E-angelo** [comment]
Looks like I will have to provide you with some recordings to look at on developercommunity, @sharwell.  As I know for certain I was getting the wonky navigation with Visual Studio 2022 that made me search for and install this extension in 2019, and further goes away when using X-Mouse for 2022.  In any case, I do appreciate your efforts with this extension as they definitely helped when I needed it back then when using 2019. 🙏

**Comment by Mike-E-angelo** [comment]
Ahhh mystery perhaps solved here, @sharwell:
https://youtrack.jetbrains.com/issue/RSRP-469556

So it appears this extension can still serve some purpose: fixing JetBrains code. 😁

**Comment by SnubbleJr** [comment]
+1 for this, R#'s broken implementation is something I doubt they'll fix quickly

**Comment by sharwell** [comment]
I find uninstalling ReSharper to be an all-around excellent move (better performance, and no longer have to deal with those bugs).

Either way, since Visual Studio's implementation of this feature is better than this extension _and_ this extension at best would make the behavior a bit worse, I have no plans to make a 2022 release.

**Comment by alexalok** [comment]
> I find uninstalling ReSharper to be an all-around excellent move (better performance, and no longer have to deal with those bugs).

While this is a valid concern about the performance part, VS functional inferiority in a vast amount of areas still outweighs the cons for many users.

**Comment by mwmcafee** [comment]
I'm not saying Resharper is the best ever, that argument is up to opinion and besides the point.
But what you are saying is you **could** let this extension work on 2022, it could be a REALLY GREAT workaround and make peoples lives easier.
But you wont allow this to go through, you wont allow this optional extension that people can choose to enable/disable, people can choose to use the default behaviour in 2022 or this inferior behaviour.
But you wont allow it just because.... You don't like another plugin?

Yes 2022 has this built in and it works. So what's the point?
Your argument you are making is you don't see why this is valuable, the answer is: another plugin has overwritten the default behaviour built into late 2019 versions and 2022 versions.
This would really add value to some people.

Please allow this to work on 2022. It is valuable to some people.
